SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Linq;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository _productRepository;

        public NavigationMenuViewComponent(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_productRepository.Products.Select(product => product.Category).Distinct().OrderBy(product => product));
        } 
    }
}

SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;
using System.Linq;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly Cart _cart;

        public CartController(IProductRepository repository, Cart cart)
        {
            _repository = repository;
            _cart = cart;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel {Cart = _cart, ReturnUrl = returnUrl});
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (null != product)
            {
                _cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (null != product)
            {
                _cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float: right">
                <small>@Model.Price.ToString("C")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float: right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="css/*.min.css"/>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error { border-color: red; background-color: #fee; }
    </style>
    <script src="jquery/dist/jquery.min.js"></script>
    <script src="jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body class="m-1 p-1">
<div class="bg-info p-2 row">
    <div class="col">
        <h4>@ViewBag.Title</h4>        
    </div>
    <div class="col-2">
        <a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">Log Out</a>
    </div>
</div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="css/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid*"/>
    <link rel="stylesheet" asp-href-include="/font-awesome/font-awesome/css/*.css"/>
    <title>SportsStore</title>
</head>
<body>
<div class="navbar navbar-dark bg-dark" role="navigation">
    <div class="row">
        <a class="col navbar-brand" href="#">SPORTS STORE</a>
        <div class="col-2 text-right ml-auto">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>
</div>
<div class="row m-1 p-1">
    <div id="categories" class="col-3"> @await Component.InvokeAsync("NavigationMenu")</div>
    <div class="col-9">@RenderBody()</div>    
</div>
</body>
</html>